// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hmm_hs_cpp_parallel
Rcpp::List hmm_hs_cpp_parallel(Rcpp::IntegerMatrix G, Rcpp::IntegerVector M, Rcpp::IntegerVector phase_vec, double r_start, std::string pi_mode, Rcpp::Nullable<Rcpp::NumericMatrix> pi_prior_in, double lambda, double epsilon, double tol, int maxit, std::string paternal_mode, Rcpp::Nullable<Rcpp::NumericMatrix> Pi_prior_in, Rcpp::Nullable<Rcpp::NumericVector> r_init, std::string epsilon_model, double epsilon_tau);
RcppExport SEXP _HalfSibMap_hmm_hs_cpp_parallel(SEXP GSEXP, SEXP MSEXP, SEXP phase_vecSEXP, SEXP r_startSEXP, SEXP pi_modeSEXP, SEXP pi_prior_inSEXP, SEXP lambdaSEXP, SEXP epsilonSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP paternal_modeSEXP, SEXP Pi_prior_inSEXP, SEXP r_initSEXP, SEXP epsilon_modelSEXP, SEXP epsilon_tauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type G(GSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type M(MSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type phase_vec(phase_vecSEXP);
    Rcpp::traits::input_parameter< double >::type r_start(r_startSEXP);
    Rcpp::traits::input_parameter< std::string >::type pi_mode(pi_modeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type pi_prior_in(pi_prior_inSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< std::string >::type paternal_mode(paternal_modeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type Pi_prior_in(Pi_prior_inSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type r_init(r_initSEXP);
    Rcpp::traits::input_parameter< std::string >::type epsilon_model(epsilon_modelSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon_tau(epsilon_tauSEXP);
    rcpp_result_gen = Rcpp::wrap(hmm_hs_cpp_parallel(G, M, phase_vec, r_start, pi_mode, pi_prior_in, lambda, epsilon, tol, maxit, paternal_mode, Pi_prior_in, r_init, epsilon_model, epsilon_tau));
    return rcpp_result_gen;
END_RCPP
}
// gamma_cpp
Rcpp::NumericVector gamma_cpp(Rcpp::IntegerMatrix G, Rcpp::IntegerVector M, Rcpp::IntegerVector phase_vec, Rcpp::NumericVector r, Rcpp::NumericMatrix pi_emis, double epsilon);
RcppExport SEXP _HalfSibMap_gamma_cpp(SEXP GSEXP, SEXP MSEXP, SEXP phase_vecSEXP, SEXP rSEXP, SEXP pi_emisSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type G(GSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type M(MSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type phase_vec(phase_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pi_emis(pi_emisSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(gamma_cpp(G, M, phase_vec, r, pi_emis, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// hmm_hs_joint_cpp
Rcpp::List hmm_hs_joint_cpp(Rcpp::List G_list, Rcpp::List M_list, Rcpp::List phase_list, double r_start, std::string pi_mode, Rcpp::Nullable<Rcpp::List> pi_prior_list_in, double lambda, double epsilon, double tol, int maxit, std::string paternal_mode, Rcpp::Nullable<Rcpp::List> Pi_prior_list_in);
RcppExport SEXP _HalfSibMap_hmm_hs_joint_cpp(SEXP G_listSEXP, SEXP M_listSEXP, SEXP phase_listSEXP, SEXP r_startSEXP, SEXP pi_modeSEXP, SEXP pi_prior_list_inSEXP, SEXP lambdaSEXP, SEXP epsilonSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP paternal_modeSEXP, SEXP Pi_prior_list_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type G_list(G_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type M_list(M_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type phase_list(phase_listSEXP);
    Rcpp::traits::input_parameter< double >::type r_start(r_startSEXP);
    Rcpp::traits::input_parameter< std::string >::type pi_mode(pi_modeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type pi_prior_list_in(pi_prior_list_inSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< std::string >::type paternal_mode(paternal_modeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type Pi_prior_list_in(Pi_prior_list_inSEXP);
    rcpp_result_gen = Rcpp::wrap(hmm_hs_joint_cpp(G_list, M_list, phase_list, r_start, pi_mode, pi_prior_list_in, lambda, epsilon, tol, maxit, paternal_mode, Pi_prior_list_in));
    return rcpp_result_gen;
END_RCPP
}
// loglik_hs_cpp
double loglik_hs_cpp(Rcpp::IntegerMatrix G, Rcpp::IntegerVector M, Rcpp::IntegerVector phase_vec, Rcpp::NumericVector r, Rcpp::NumericMatrix pi_emis, double epsilon);
RcppExport SEXP _HalfSibMap_loglik_hs_cpp(SEXP GSEXP, SEXP MSEXP, SEXP phase_vecSEXP, SEXP rSEXP, SEXP pi_emisSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type G(GSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type M(MSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type phase_vec(phase_vecSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pi_emis(pi_emisSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_hs_cpp(G, M, phase_vec, r, pi_emis, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// simulate_offspring_cpp
Rcpp::List simulate_offspring_cpp(Rcpp::IntegerVector M, Rcpp::NumericMatrix pi_true, Rcpp::NumericVector r_true, int n_offspring, double error_rate, bool keep_paths, Rcpp::Nullable<Rcpp::IntegerVector> z_phase_in);
RcppExport SEXP _HalfSibMap_simulate_offspring_cpp(SEXP MSEXP, SEXP pi_trueSEXP, SEXP r_trueSEXP, SEXP n_offspringSEXP, SEXP error_rateSEXP, SEXP keep_pathsSEXP, SEXP z_phase_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type M(MSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type pi_true(pi_trueSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type r_true(r_trueSEXP);
    Rcpp::traits::input_parameter< int >::type n_offspring(n_offspringSEXP);
    Rcpp::traits::input_parameter< double >::type error_rate(error_rateSEXP);
    Rcpp::traits::input_parameter< bool >::type keep_paths(keep_pathsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type z_phase_in(z_phase_inSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_offspring_cpp(M, pi_true, r_true, n_offspring, error_rate, keep_paths, z_phase_in));
    return rcpp_result_gen;
END_RCPP
}
// pairwise_rf_estimation_multi_parallel_cpp
Rcpp::List pairwise_rf_estimation_multi_parallel_cpp(Rcpp::List G_list, Rcpp::List M_list, double lambda, double q0, double tol, int maxit, double tiny, bool share_q_across_dams, bool return_diagnostics, bool verbose, std::string optimizer);
RcppExport SEXP _HalfSibMap_pairwise_rf_estimation_multi_parallel_cpp(SEXP G_listSEXP, SEXP M_listSEXP, SEXP lambdaSEXP, SEXP q0SEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP tinySEXP, SEXP share_q_across_damsSEXP, SEXP return_diagnosticsSEXP, SEXP verboseSEXP, SEXP optimizerSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type G_list(G_listSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type M_list(M_listSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type q0(q0SEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tiny(tinySEXP);
    Rcpp::traits::input_parameter< bool >::type share_q_across_dams(share_q_across_damsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_diagnostics(return_diagnosticsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< std::string >::type optimizer(optimizerSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_rf_estimation_multi_parallel_cpp(G_list, M_list, lambda, q0, tol, maxit, tiny, share_q_across_dams, return_diagnostics, verbose, optimizer));
    return rcpp_result_gen;
END_RCPP
}
// two_point_pair_grid_cpp
Rcpp::List two_point_pair_grid_cpp(Rcpp::IntegerMatrix C3, Rcpp::IntegerVector niO, Rcpp::IntegerVector njO, double q_i, double q_j, double tol, int maxit, double tiny);
RcppExport SEXP _HalfSibMap_two_point_pair_grid_cpp(SEXP C3SEXP, SEXP niOSEXP, SEXP njOSEXP, SEXP q_iSEXP, SEXP q_jSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP tinySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type C3(C3SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type niO(niOSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type njO(njOSEXP);
    Rcpp::traits::input_parameter< double >::type q_i(q_iSEXP);
    Rcpp::traits::input_parameter< double >::type q_j(q_jSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tiny(tinySEXP);
    rcpp_result_gen = Rcpp::wrap(two_point_pair_grid_cpp(C3, niO, njO, q_i, q_j, tol, maxit, tiny));
    return rcpp_result_gen;
END_RCPP
}
// two_point_pair_newton_cpp
Rcpp::List two_point_pair_newton_cpp(Rcpp::IntegerMatrix C3, Rcpp::IntegerVector niO, Rcpp::IntegerVector njO, double q_i, double q_j, double tol, int maxit, double tiny);
RcppExport SEXP _HalfSibMap_two_point_pair_newton_cpp(SEXP C3SEXP, SEXP niOSEXP, SEXP njOSEXP, SEXP q_iSEXP, SEXP q_jSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP tinySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type C3(C3SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type niO(niOSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type njO(njOSEXP);
    Rcpp::traits::input_parameter< double >::type q_i(q_iSEXP);
    Rcpp::traits::input_parameter< double >::type q_j(q_jSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tiny(tinySEXP);
    rcpp_result_gen = Rcpp::wrap(two_point_pair_newton_cpp(C3, niO, njO, q_i, q_j, tol, maxit, tiny));
    return rcpp_result_gen;
END_RCPP
}
// two_point_pair_bench_cpp
Rcpp::List two_point_pair_bench_cpp(Rcpp::IntegerMatrix C3, Rcpp::IntegerVector niO, Rcpp::IntegerVector njO, double q_i, double q_j, int nrep, std::string method, double tol, int maxit, double tiny);
RcppExport SEXP _HalfSibMap_two_point_pair_bench_cpp(SEXP C3SEXP, SEXP niOSEXP, SEXP njOSEXP, SEXP q_iSEXP, SEXP q_jSEXP, SEXP nrepSEXP, SEXP methodSEXP, SEXP tolSEXP, SEXP maxitSEXP, SEXP tinySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type C3(C3SEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type niO(niOSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type njO(njOSEXP);
    Rcpp::traits::input_parameter< double >::type q_i(q_iSEXP);
    Rcpp::traits::input_parameter< double >::type q_j(q_jSEXP);
    Rcpp::traits::input_parameter< int >::type nrep(nrepSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type tiny(tinySEXP);
    rcpp_result_gen = Rcpp::wrap(two_point_pair_bench_cpp(C3, niO, njO, q_i, q_j, nrep, method, tol, maxit, tiny));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HalfSibMap_hmm_hs_cpp_parallel", (DL_FUNC) &_HalfSibMap_hmm_hs_cpp_parallel, 15},
    {"_HalfSibMap_gamma_cpp", (DL_FUNC) &_HalfSibMap_gamma_cpp, 6},
    {"_HalfSibMap_hmm_hs_joint_cpp", (DL_FUNC) &_HalfSibMap_hmm_hs_joint_cpp, 12},
    {"_HalfSibMap_loglik_hs_cpp", (DL_FUNC) &_HalfSibMap_loglik_hs_cpp, 6},
    {"_HalfSibMap_simulate_offspring_cpp", (DL_FUNC) &_HalfSibMap_simulate_offspring_cpp, 7},
    {"_HalfSibMap_pairwise_rf_estimation_multi_parallel_cpp", (DL_FUNC) &_HalfSibMap_pairwise_rf_estimation_multi_parallel_cpp, 11},
    {"_HalfSibMap_two_point_pair_grid_cpp", (DL_FUNC) &_HalfSibMap_two_point_pair_grid_cpp, 8},
    {"_HalfSibMap_two_point_pair_newton_cpp", (DL_FUNC) &_HalfSibMap_two_point_pair_newton_cpp, 8},
    {"_HalfSibMap_two_point_pair_bench_cpp", (DL_FUNC) &_HalfSibMap_two_point_pair_bench_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_HalfSibMap(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
