# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hmm_hs_cpp_parallel <- function(G, M, phase_vec, r_start = 0.05, pi_mode = "per_marker", pi_prior_in = NULL, lambda = 20.0, epsilon = 1e-3, tol = 1e-6, maxit = 200L, paternal_mode = "per_marker", Pi_prior_in = NULL, r_init = NULL, epsilon_model = "global", epsilon_tau = 100.0) {
    .Call(`_HalfSibMap_hmm_hs_cpp_parallel`, G, M, phase_vec, r_start, pi_mode, pi_prior_in, lambda, epsilon, tol, maxit, paternal_mode, Pi_prior_in, r_init, epsilon_model, epsilon_tau)
}

gamma_cpp <- function(G, M, phase_vec, r, pi_emis, epsilon = 1e-3) {
    .Call(`_HalfSibMap_gamma_cpp`, G, M, phase_vec, r, pi_emis, epsilon)
}

hmm_hs_joint_cpp <- function(G_list, M_list, phase_list, r_start = 0.05, pi_mode = "per_marker", pi_prior_list_in = NULL, lambda = 20.0, epsilon = 1e-3, tol = 1e-6, maxit = 200L, paternal_mode = "per_marker", Pi_prior_list_in = NULL) {
    .Call(`_HalfSibMap_hmm_hs_joint_cpp`, G_list, M_list, phase_list, r_start, pi_mode, pi_prior_list_in, lambda, epsilon, tol, maxit, paternal_mode, Pi_prior_list_in)
}

loglik_hs_cpp <- function(G, M, phase_vec, r, pi_emis, epsilon = 1e-3) {
    .Call(`_HalfSibMap_loglik_hs_cpp`, G, M, phase_vec, r, pi_emis, epsilon)
}

simulate_offspring_cpp <- function(M, pi_true, r_true, n_offspring, error_rate = 0.0, keep_paths = FALSE, z_phase_in = NULL) {
    .Call(`_HalfSibMap_simulate_offspring_cpp`, M, pi_true, r_true, n_offspring, error_rate, keep_paths, z_phase_in)
}

pairwise_rf_estimation_multi_parallel_cpp <- function(G_list, M_list, lambda = 20.0, q0 = 0.5, tol = 1e-6, maxit = 200L, tiny = 1e-12, share_q_across_dams = FALSE, return_diagnostics = FALSE, verbose = FALSE, optimizer = "auto") {
    .Call(`_HalfSibMap_pairwise_rf_estimation_multi_parallel_cpp`, G_list, M_list, lambda, q0, tol, maxit, tiny, share_q_across_dams, return_diagnostics, verbose, optimizer)
}

two_point_pair_grid_cpp <- function(C3, niO, njO, q_i, q_j, tol = 1e-6, maxit = 200L, tiny = 1e-12) {
    .Call(`_HalfSibMap_two_point_pair_grid_cpp`, C3, niO, njO, q_i, q_j, tol, maxit, tiny)
}

two_point_pair_newton_cpp <- function(C3, niO, njO, q_i, q_j, tol = 1e-6, maxit = 100L, tiny = 1e-12) {
    .Call(`_HalfSibMap_two_point_pair_newton_cpp`, C3, niO, njO, q_i, q_j, tol, maxit, tiny)
}

two_point_pair_bench_cpp <- function(C3, niO, njO, q_i, q_j, nrep = 10000L, method = "newton", tol = 1e-6, maxit = 200L, tiny = 1e-12) {
    .Call(`_HalfSibMap_two_point_pair_bench_cpp`, C3, niO, njO, q_i, q_j, nrep, method, tol, maxit, tiny)
}

